version: '3.8'
services:

  db:
    image: postgres
    restart: always
    network_mode: host
    env_file:
      - ./.env
    ports:
      - 5432:5432

    volumes:
      - ./data:/var/lib/postgresql/data

  frontend:
    network_mode: host  
    build: ./frontend
    ports:
      - 3000:3000

    depends_on:
      - backend


  backend:
    build: ./backend
    network_mode: host

    ports:
      - 8000:8000

    depends_on:
      - db

